name: Deploy website on push

on:
  push:
    branches: -main

jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Sync files
        uses: samKirkland/FTP-Deploy-Actions@4.1.0
        with:
          server: ftp.acebridge.ng
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          server-dir: /
